#!/bin/bash

set -e

PROJECT_NAME="hauth"

echo "$(date): reloading the REPL..."

# This assumes the REPL is started in the first pane
tmux send-keys -t "$PROJECT_NAME:0" ":!clear" Enter
tmux send-keys -t "$PROJECT_NAME:0" ":reload" Enter
if [ -z "$1" ]; then
    tmux send-keys -t "$PROJECT_NAME:0" ":main" Enter
else
    if [ "$1" != "none" ]; then
        tmux send-keys -t "$PROJECT_NAME:0" ":main --match \"$1\"" Enter
    fi
fi
